# Generated by Django 5.0.1 on 2026-03-13 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ticket_type', models.CharField(choices=[('repair', 'Réparation'), ('diagnostic', 'Diagnostic'), ('upgrade', 'Upgrade'), ('preventive', 'Préventif'), ('cleaning', 'Nettoyage')], default='repair', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('assigned', 'Assigné'), ('in_progress', 'En cours'), ('waiting_parts', 'Attente pièces'), ('pending_review', 'En attente validation'), ('resolved', 'Résolu'), ('closed', 'Fermé'), ('cancelled', 'Annulé')], default='open', max_length=20)),
                ('assigned_tech', models.CharField(blank=True, max_length=100)),
                ('reported_by', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='inventory.asset')),
            ],
            options={
                'verbose_name': 'Ticket de maintenance',
                'verbose_name_plural': 'Tickets de maintenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='maintenance.maintenanceticket')),
            ],
            options={
                'verbose_name': 'Historique statut',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.maintenanceticket')),
            ],
            options={
                'verbose_name': 'Commentaire ticket',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_name', models.CharField(max_length=200)),
                ('part_ref', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.maintenanceticket')),
            ],
            options={
                'verbose_name': 'Pièce utilisée',
            },
        ),
    ]
