# Generated by Django 5.0.1 on 2026-03-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='internal_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
