# Generated by Django 5.0.1 on 2026-03-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition_state',
            field=models.CharField(choices=[('new', 'Neuf'), ('used', 'Occasion'), ('damaged', 'Endommagé')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactif'), ('maintenance', 'En maintenance'), ('repair', 'En réparation'), ('broken', 'En panne'), ('archived', 'Archivé')], default='active', max_length=15),
        ),
    ]
