# Generated by Django 5.0.1 on 2026-03-26 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userprofile'),
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='error_correction',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='format',
            field=models.CharField(default='PNG', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='size',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='uuid_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['uuid_token'], name='scanner_qrc_uuid_to_4630b8_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['code'], name='scanner_qrc_code_a459c8_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['asset', '-created_at'], name='scanner_qrc_asset_i_720ad7_idx'),
        ),
    ]
