# Generated by Django 5.0.1 on 2026-03-27 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userprofile'),
        ('scanner', '0002_qrcode_code_qrcode_error_correction_qrcode_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(choices=[('usb', 'USB'), ('bluetooth', 'Bluetooth'), ('ethernet', 'Ethernet/WiFi'), ('network', 'Network Printer')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('device_path', models.CharField(blank=True, max_length=255)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('dpi', models.PositiveIntegerField(default=203)),
                ('speed', models.PositiveIntegerField(default=3)),
                ('density', models.PositiveIntegerField(default=10)),
                ('paper_width_mm', models.PositiveIntegerField(default=50)),
                ('paper_height_mm', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('30x20', '30mm x 20mm (Petit matériel)'), ('50x30', '50mm x 30mm (Standard)'), ('70x40', '70mm x 40mm (Grand matériel)'), ('80x50', '80mm x 50mm (Rack/Serveur)'), ('100x50', '100mm x 50mm (Armoire)')], default='50x30', max_length=20)),
                ('width_mm', models.PositiveIntegerField(default=50)),
                ('height_mm', models.PositiveIntegerField(default=30)),
                ('qr_size_mm', models.PositiveIntegerField(default=25)),
                ('qr_position_x_mm', models.PositiveIntegerField(default=5)),
                ('qr_position_y_mm', models.PositiveIntegerField(default=5)),
                ('font_size_title', models.PositiveIntegerField(default=10)),
                ('font_size_text', models.PositiveIntegerField(default=8)),
                ('show_serial', models.BooleanField(default=True)),
                ('show_internal_code', models.BooleanField(default=True)),
                ('show_category', models.BooleanField(default=True)),
                ('show_location', models.BooleanField(default=True)),
                ('show_purchase_date', models.BooleanField(default=False)),
                ('show_warranty', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('asset_ids', models.JSONField(help_text='Liste des asset IDs à imprimer')),
                ('copies', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='print_jobs/%Y/%m/')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.printer')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.printtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='printer',
            name='default_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.printtemplate'),
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=100)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.printjob')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-printed_at'],
                'indexes': [models.Index(fields=['asset', '-printed_at'], name='scanner_pri_asset_i_3b2542_idx'), models.Index(fields=['printed_by', '-printed_at'], name='scanner_pri_printed_8c8c09_idx')],
            },
        ),
    ]
