# Generated by Django 5.2.11 on 2026-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_printer_printtemplate_printjob_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='url',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(default='default_qr_code', help_text='Format: qr_asset_<id>_<uuid>', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, help_text='Image PNG du QR Code', null=True, upload_to='qr_codes/%Y/%m/'),
        ),
    ]
