# Generated by Django 5.0.1 on 2026-03-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_qrcode_options_remove_qrcode_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='template',
        ),
        migrations.RemoveField(
            model_name='printlog',
            name='job',
        ),
        migrations.RemoveField(
            model_name='printlog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='printlog',
            name='printed_by',
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
        migrations.DeleteModel(
            name='PrintTemplate',
        ),
        migrations.DeleteModel(
            name='PrintJob',
        ),
        migrations.DeleteModel(
            name='PrintLog',
        ),
    ]
