# Generated by Django 5.0.1 on 2026-04-04 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_remove_printjob_printer_remove_printjob_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='code_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='scanned_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='uuid_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Token unique pour l'URL de scan (ex: qr_asset_<id>_<uuid>)", unique=True),
        ),
    ]
