# Generated by Django 5.0.1 on 2026-04-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userprofile'),
        ('maintenance', '0001_initial'),
        ('scanner', '0006_scanlog_code_type_scanlog_scanned_code_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannedasset',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='scannedasset',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='scannedasset',
            name='scan_log',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='scanned_asset',
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Code Scannable (QR/Barres)', 'verbose_name_plural': 'Codes Scannables (QR/Barres)'},
        ),
        migrations.AddField(
            model_name='qrcode',
            name='code_type',
            field=models.CharField(choices=[('qr_code', 'QR Code (2D)'), ('barcode_serial', 'Code-Barres Serial (1D)'), ('barcode_internal', 'Code-Barres Interne (1D)'), ('barcode_reference', 'Code-Barres Référence Stock')], default='qr_code', help_text='Format du code: QR, Barcode Serial, Barcode Internal', max_length=30),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='inventory.asset'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='location_at_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='scan_context',
            field=models.CharField(choices=[('inventory', 'Inventaire'), ('maintenance', 'Maintenance'), ('movement', 'Mouvement'), ('audit', 'Audit'), ('reception', 'Réception')], default='inventory', help_text='Pourquoi ce scan a été fait', max_length=30),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='stock.stockitem'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='maintenance.maintenanceticket'),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='code_type',
            field=models.CharField(choices=[('qr_code', 'QR Code (2D)'), ('barcode_serial', 'Code-Barres Serial (1D)'), ('barcode_internal', 'Code-Barres Interne (1D)'), ('barcode_reference', 'Code-Barres Référence Stock')], default='qr_code', max_length=30),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='scanned_code',
            field=models.CharField(blank=True, help_text='Code brut scanné', max_length=255),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['asset', '-created_at'], name='scanner_sca_asset_i_8496bf_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['scanned_by', '-created_at'], name='scanner_sca_scanned_d27140_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['scan_context', '-created_at'], name='scanner_sca_scan_co_f0712e_idx'),
        ),
        migrations.DeleteModel(
            name='ScannedAsset',
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
    ]
