# Generated by Django 5.0.1 on 2026-04-05 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_remove_scannedasset_asset_remove_scannedasset_qrcode_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='stock.stockitem'),
        ),
    ]
