# Generated by Django 5.0.1 on 2026-04-06 10:44
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [ ('scanner', '0008_qrcode_stock_item' ), ]
    operations = [
        migrations.RenameModel(
            old_name='QRCode',
            new_name='ScannableCode',
        ),
        migrations.AlterModelOptions(
            name='scannablecode',
            options={'verbose_name': 'Code Scannable', 'verbose_name_plural': 'Codes Scannables'},
        ),
    ]
