# Generated by Django 5.0.1 on 2026-04-06 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userprofile'),
        ('scanner', '0009_rename_qrcode_to_scannablecode'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scannablecode',
            name='scanner_qrc_uuid_to_4630b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='scannablecode',
            name='scanner_qrc_code_a459c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='scannablecode',
            name='scanner_qrc_asset_i_720ad7_idx',
        ),
        migrations.RenameField(
            model_name='scanlog',
            old_name='qrcode',
            new_name='ScannableCode',
        ),
        migrations.RemoveField(
            model_name='scannablecode',
            name='error_correction',
        ),
        migrations.RemoveField(
            model_name='scannablecode',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='code_type',
            field=models.CharField(choices=[('qr_code', 'QR Code (2D)'), ('barcode_128', 'Code 128 (1D)'), ('barcode_ean13', 'EAN-13 (1D)'), ('barcode_ean8', 'EAN-8 (1D)'), ('barcode_39', 'Code 39 (1D)')], default='qr_code', max_length=30),
        ),
        migrations.AlterField(
            model_name='scannablecode',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scannable_codes', to='inventory.asset'),
        ),
        migrations.AlterField(
            model_name='scannablecode',
            name='code',
            field=models.CharField(db_index=True, help_text='Valeur du code scanné', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='scannablecode',
            name='code_type',
            field=models.CharField(choices=[('qr_code', 'QR Code (2D)'), ('barcode_128', 'Code 128 (1D)'), ('barcode_ean13', 'EAN-13 (1D)'), ('barcode_ean8', 'EAN-8 (1D)'), ('barcode_39', 'Code 39 (1D)')], default='qr_code', max_length=30),
        ),
        migrations.AlterField(
            model_name='scannablecode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scannable_codes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='scannablecode',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scannable_codes', to='stock.stockitem'),
        ),
        migrations.AlterField(
            model_name='scannablecode',
            name='uuid_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
